# Generated by Django 5.0.2 on 2024-03-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakka', '0002_application_server_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_name',
            field=models.CharField(help_text='Unique name for the application. Contains lowercase letters, numbers, and underscores. No spaces allowed.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='server_api_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
