# Generated by Django 5.0.2 on 2024-03-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakka', '0003_alter_application_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='server_api_key',
            field=models.CharField(blank=True, help_text='Copy this key to the target application. Set this field to null once you copied the key using Actions.', max_length=50, null=True),
        ),
    ]
