# Generated by Django 5.0.2 on 2024-03-15 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wakka', '0007_user_verified_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnetimeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jti', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
